namespace NKM.Templet;

public enum NKM_WARFARE_ENEMY_ACTION_TYPE
{
	NWEAT_NONE,
	NWEAT_DEFENSE,
	NWEAT_NEAREST_ATK,
	NWEAT_ONLY_FLAG_SHIP_ATK,
	NWEAT_FIND_WIN_TILE,
	NWEAT_FIND_LOSE_TILE,
	NWEAT_PATROL
}
