namespace NKM.Templet;

public enum NKM_DIVE_EVENT_TYPE
{
	NDET_NONE,
	NDET_DUNGEON,
	NDET_DUNGEON_BOSS,
	NDET_ITEM,
	NDET_UNIT,
	NDET_BLANK,
	NDET_REPAIR,
	NDET_SUPPLY,
	NDET_LOSTSHIP_RANDOM,
	NDET_LOSTSHIP_ITEM,
	NDET_LOSTSHIP_UNIT,
	NDET_LOSTSHIP_REPAIR,
	NDET_LOSTSHIP_SUPPLY,
	NDET_BEACON_RANDOM,
	NDET_BEACON_DUNGEON,
	NDET_BEACON_BLANK,
	NDET_BEACON_ITEM,
	NDET_BEACON_UNIT,
	NDET_BEACON_STORM,
	NDET_ARTIFACT
}
