namespace NKM.Templet;

public enum WARFARE_GAME_MISSION_TYPE
{
	WFMT_NONE,
	WFMT_CLEAR,
	WFMT_ALLKILL,
	WFMT_PHASE,
	WFMT_NO_SHIPWRECK,
	WFMT_KILL,
	WFMT_FIRST_ATTACK,
	WFMT_ASSIST,
	WFMT_CONTAINER,
	WFMT_NOSUPPLY_WIN,
	WFMT_NOSUPPLY_ALLKILL
}
