namespace NKM.Shop;

public enum PURCHASE_EVENT_REWARD_TYPE
{
	FIRST_PURCHASE_CHANGE_REWARD_VALUE,
	SUBSCRIBE_7_DAYS,
	SUBSCRIBE_10_DAYS,
	SUBSCRIBE_15_DAYS,
	SUBSCRIBE_18_DAYS,
	SUBSCRIBE_30_DAYS,
	INCREACE_PRICE_PER_PURCHASE_COUNT,
	LEVELUP_PACKAGE,
	CONSUMER_PACKAGE,
	NONE
}
