namespace NKM;

public enum DUNGEON_GAME_MISSION_TYPE
{
	DGMT_NONE,
	DGMT_CLEAR,
	DGMT_TIME,
	DGMT_COST,
	DGMT_RESPAWN,
	DGMT_SHIP_HP_DAMAGE,
	DGMT_DECKCOUNT_SOLDIER,
	DGMT_DECKCOUNT_MECHANIC,
	DGMT_DECKCOUNT_COUNTER,
	DGMT_DECKCOUNT_DEFENDER,
	DGMT_DECKCOUNT_STRIKER,
	DGMT_DECKCOUNT_RANGER,
	DGMT_DECKCOUNT_SNIPER,
	DGMT_DECKCOUNT_TOWER,
	DGMT_DECKCOUNT_SIEGE,
	DGMT_DECKCOUNT_SUPPORTER,
	DGMT_WAVE_CLEAR_LEVEL,
	DGMT_TEAM_A_KILL_COUNT,
	DGMT_TEAM_B_KILL_COUNT
}
