namespace NKM;

public enum DUNGEON_RESPAWN_UNIT_TEMPLET_TYPE
{
	BOSS_RESPAWN_UNIT,
	DUNGEON_DECK,
	DUNGEON_UNIT_RESPAWN_A,
	DUNGEON_UNIT_RESPAWN_B,
	WAVE_DUNGEON_UNIT_RESPAWN_A,
	WAVE_DUNGEON_UNIT_RESPAWN_B
}
