namespace NKM;

public enum NKM_FIND_TARGET_TYPE
{
	NFTT_INVALID,
	NFTT_NO,
	NFTT_NEAR_ENEMY,
	NFTT_NEAR_ENEMY_AIR_FIRST,
	NFTT_NEAR_ENEMY_LAND,
	NFTT_NEAR_ENEMY_AIR,
	NFTT_NEAR_ENEMY_LAND_RANGER_SUPPORTER_SNIPER_FIRST,
	NFTT_FAR_ENEMY,
	NFTT_FAR_ENEMY_LAND,
	NFTT_FAR_ENEMY_AIR,
	NFTT_FAR_ENEMY_BOSS_LAST,
	NFTT_FAR_ENEMY_LAND_BOSS_LAST,
	NFTT_FAR_ENEMY_AIR_BOSS_LAST,
	NFTT_ENEMY_BOSS_ONLY,
	NFTT_ENEMY_BOSS,
	NFTT_ENEMY_BOSS_LAND,
	NFTT_ENEMY_BOSS_AIR,
	NFTT_NEAR_MY_TEAM,
	NFTT_NEAR_MY_TEAM_LAND,
	NFTT_NEAR_MY_TEAM_AIR,
	NFTT_NEAR_MY_TEAM_LOW_HP,
	NFTT_NEAR_MY_TEAM_LOW_HP_LAND,
	NFTT_NEAR_MY_TEAM_LOW_HP_AIR,
	NFTT_FAR_MY_TEAM,
	NFTT_FAR_MY_TEAM_LAND,
	NFTT_FAR_MY_TEAM_AIR
}
