namespace NKM;

public enum NKM_EVENT_START_CONDITION_TYPE : byte
{
	NONE,
	UNIT_STATE_START,
	UNIT_STATE_END,
	ENEMY_BOSS_HP_RATE_LESS,
	TARGET_ALLY_UNIT_HP_RATE_LESS,
	TARGET_ENEMY_UNIT_HP_RATE_LESS,
	HAVE_SUMMON_COST
}
