namespace NKM;

public enum NKM_EVENT_ACTION_TYPE : byte
{
	INVALID,
	GAME_EVENT,
	SET_ENEMY_BOSS_HP_RATE,
	SET_UNIT_HYPER_FULL,
	KILL_ALL_TAGGED_UNIT,
	ADD_EVENTTAG,
	SET_EVENTTAG,
	NEAT_RESPAWN_COST_A_TEAM,
	NEAT_RESPAWN_COST_B_TEAM,
	ADD_TEAM_A_EXTRA_RESPAWN_COST,
	ADD_TEAM_B_EXTRA_RESPAWN_COST,
	UNLOCK_TUTORIAL_GAME_RE_RESPAWN,
	CHANGE_BGM,
	CHANGE_BGM_TRACK,
	FORCE_WIN,
	FORCE_LOSE,
	SET_UNIT_STATE,
	SET_ENEMY_UNIT_STATE,
	HUD_ALERT,
	POPUP_MESSAGE,
	MAP_ANIMATION,
	SET_GAME_TIME,
	DELTA_GAME_TIME,
	CHANGE_CAMERA
}
