namespace NKM;

public enum NKM_UNIT_EVENT_MARK : byte
{
	NUEM_INVALID,
	NUEM_GET_AGRO,
	NUEM_ALLY_RESPAWN_COST,
	NUEM_ENEMY_RESPAWN_COST,
	NUEM_RE_RESPAWN_EFFECT,
	NUEM_TACTICAL_COMMAND_MYTEAM_EFFECT,
	NUEM_TACTICAL_COMMAND_ENEMY_EFFECT,
	NUEM_DISPEL,
	NUEM_INSTA_KILL
}
