namespace NKM;

public enum NKM_CITY_BUILDING_STAT
{
	CBS_MISSION_CITY_EXP_RATE,
	CBS_MISSION_UNIT_EXP_RATE,
	CBS_MISSION_CREDIT_RATE,
	CBS_MISSION_ETERNIUM_RATE,
	CBS_MISSION_INFORMATION_RATE,
	CBS_MISSION_TIME_REDUCE_RATE,
	CBS_MISSION_SUCCSSES_RATE,
	CBS_MISSION_RANK_SEARCH_RATE,
	CBS_EVENT_SPECIAL_SEARCH_RATE,
	CBS_DIVE_INFORMATION_REDUCE_RATE,
	CBS_DIVE_SEARCH_RATE,
	CBS_RAID_DEFENCE_LEVEL,
	CBS_RAID_DEFENCE_COST_REDUCE_RATE,
	CBS_RAID_SEARCH_RATE
}
