namespace NKM;

public enum NKM_STATE_CHANGE_PRIORITY : short
{
	NSCP_INVALID,
	NSCP_NORMAL,
	NSCP_NORMAL_CRASH,
	NSCP_SKILL,
	NSCP_SKILL_CRASH,
	NSCP_HYPER,
	NSCP_HYPER_CRASH,
	NSCP_SUPER,
	NSCP_SUPER_CRASH,
	NSCP_INVINCIBLE,
	NSCP_FORCE,
	NSCP_DIE
}
