namespace NKM;

public enum NKM_GAME_EVENT_TYPE : byte
{
	NGET_INVALID,
	NGET_TACTICAL_COMMAND,
	NGET_TC_COMBO_SUCCESS,
	NGET_TC_COMBO_FAIL,
	NGET_TC_COMBO_SKILL_SUCCESS,
	NGET_TC_COMBO_SKILL_REAL_APPLY_AFTER_SUCCESS,
	NGET_TC_COMBO_COOL_TIME_ON,
	NGET_KILL_COUNT,
	NGET_AUTO_RESPAWN_WARNING,
	NGET_AUTO_RESPAWN_SET,
	NGET_COST_RETURN
}
