namespace NKM;

public enum NKM_ITEM_MISC_SUBTYPE : short
{
	NONE,
	IMST_EQUIP_CHOICE_SET_OPTION,
	IMST_INTERIOR_DECO,
	IMST_INTERIOR_FURNITURE,
	IMST_OPERATOR_CHOICE_SKILL,
	IMST_UNIT_CHOICE_LEVEL_100,
	IMST_UNIT_CHOICE_LEVEL_110,
	IMST_UNIT_CHOICE_LEVEL_120,
	IMST_EQUIP_CHOICE_OPTION_CUSTOM
}
