namespace NKM;

public enum NKM_EFFECT_PARENT_TYPE
{
	NEPT_NUM_GAME_BATTLE_EFFECT,
	NEPT_NUF_BEFORE_HUD_EFFECT,
	NEPT_NUF_BEFORE_HUD_CONTROL_EFFECT,
	NEPT_NUF_AFTER_HUD_EFFECT,
	NEPT_NUF_AFTER_UI_EFFECT
}
