namespace NKC;

public enum AnimationEventType
{
	NO_EVENT,
	FINISH_EVENT,
	ANIMATION_SPINE,
	ANIMATION_NAME_SPINE,
	ANIMATION_UNITY,
	EFFECT_SPAWN,
	EFFECT_SPAWN_FOLLOW,
	SET_MOVE_SPEED,
	SET_POSITION,
	PLAY_SOUND,
	PLAY_EMOTION,
	SET_ABSOLUTE_MOVE_SPEED,
	INVERT_MODEL_X,
	INVERT_MODEL_X_BY_DIRECTION,
	FLIP_MODEL_X,
	OFFICE_CHAR_SHADOW
}
