namespace NKC;

public enum BUILD_OPTIONS
{
	EXCLUDE_LOCKED_UNIT,
	EXCLUDE_DECKED_UNIT,
	HIDE_DECKED_UNIT,
	PUSHBACK_UNSELECTABLE,
	INCLUDE_UNDECKABLE_UNIT,
	IGNORE_CITY_STATE,
	IGNORE_WORLD_MAP_LEADER,
	INCLUDE_SEIZURE,
	DESCENDING,
	USE_DECKED_STATE,
	USE_LOCKED_STATE,
	USE_LOBBY_STATE
}
