namespace NKC;

public enum NKC_SCEN_STATE : short
{
	NSS_INVALID,
	NSS_CHANGE_START,
	NSS_DATA_REQ_WAIT,
	NSS_LOADING_UI,
	NSS_LOADING_UI_COMPLETE_WAIT,
	NSS_LOADING,
	NSS_LOADING_LAST,
	NSS_LOADING_COMPLETE_WAIT,
	NSS_LOADING_COMPLETE,
	NSS_START,
	NSS_END,
	NSS_FAIL
}
