namespace NKC;

public enum NKC_GAME_OPTION_ALARM_GROUP
{
	ALLOW_ALL_ALARM,
	WORLD_MAP_MISSION_COMPLETE,
	RESOURCE_SUPPLY_COMPLETE,
	PVP_POINT_COMPLETE,
	CRAFT_COMPLETE,
	LONG_TERM_NOT_CONNECTED_NOTIFY,
	GUILD_DUNGEON_NOTIFY,
	MAX
}
